export interface CountryDialCode {
  code: string
  name: string
  dialCode: string
  flag: string
}

const flag = (c: string) => `https://flagcdn.com/w40/${c.toLowerCase()}.png`

export const COUNTRIES: CountryDialCode[] = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: flag('AF') },
  { code: 'AL', name: 'Albania', dialCode: '+355', flag: flag('AL') },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: flag('DZ') },
  { code: 'AO', name: 'Angola', dialCode: '+244', flag: flag('AO') },
  { code: 'AR', name: 'Argentina', dialCode: '+54', flag: flag('AR') },
  { code: 'AM', name: 'Armenia', dialCode: '+374', flag: flag('AM') },
  { code: 'AU', name: 'Australia', dialCode: '+61', flag: flag('AU') },
  { code: 'AT', name: 'Austria', dialCode: '+43', flag: flag('AT') },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', flag: flag('AZ') },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', flag: flag('BH') },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: flag('BD') },
  { code: 'BB', name: 'Barbados', dialCode: '+1246', flag: flag('BB') },
  { code: 'BY', name: 'Belarus', dialCode: '+375', flag: flag('BY') },
  { code: 'BE', name: 'Belgium', dialCode: '+32', flag: flag('BE') },
  { code: 'BZ', name: 'Belize', dialCode: '+501', flag: flag('BZ') },
  { code: 'BJ', name: 'Benin', dialCode: '+229', flag: flag('BJ') },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', flag: flag('BO') },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flag: flag('BA') },
  { code: 'BW', name: 'Botswana', dialCode: '+267', flag: flag('BW') },
  { code: 'BR', name: 'Brazil', dialCode: '+55', flag: flag('BR') },
  { code: 'BN', name: 'Brunei', dialCode: '+673', flag: flag('BN') },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', flag: flag('BG') },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: flag('BF') },
  { code: 'BI', name: 'Burundi', dialCode: '+257', flag: flag('BI') },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', flag: flag('KH') },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', flag: flag('CM') },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: flag('CA') },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', flag: flag('CF') },
  { code: 'TD', name: 'Chad', dialCode: '+235', flag: flag('TD') },
  { code: 'CL', name: 'Chile', dialCode: '+56', flag: flag('CL') },
  { code: 'CN', name: 'China', dialCode: '+86', flag: flag('CN') },
  { code: 'CO', name: 'Colombia', dialCode: '+57', flag: flag('CO') },
  { code: 'KM', name: 'Comoros', dialCode: '+269', flag: flag('KM') },
  { code: 'CG', name: 'Congo', dialCode: '+242', flag: flag('CG') },
  { code: 'CD', name: 'DR Congo', dialCode: '+243', flag: flag('CD') },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: flag('CR') },
  { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225', flag: flag('CI') },
  { code: 'HR', name: 'Croatia', dialCode: '+385', flag: flag('HR') },
  { code: 'CU', name: 'Cuba', dialCode: '+53', flag: flag('CU') },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', flag: flag('CY') },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', flag: flag('CZ') },
  { code: 'DK', name: 'Denmark', dialCode: '+45', flag: flag('DK') },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', flag: flag('DJ') },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1809', flag: flag('DO') },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', flag: flag('EC') },
  { code: 'EG', name: 'Egypt', dialCode: '+20', flag: flag('EG') },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', flag: flag('SV') },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flag: flag('GQ') },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', flag: flag('ER') },
  { code: 'EE', name: 'Estonia', dialCode: '+372', flag: flag('EE') },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: flag('ET') },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', flag: flag('FJ') },
  { code: 'FI', name: 'Finland', dialCode: '+358', flag: flag('FI') },
  { code: 'FR', name: 'France', dialCode: '+33', flag: flag('FR') },
  { code: 'GA', name: 'Gabon', dialCode: '+241', flag: flag('GA') },
  { code: 'GM', name: 'Gambia', dialCode: '+220', flag: flag('GM') },
  { code: 'GE', name: 'Georgia', dialCode: '+995', flag: flag('GE') },
  { code: 'DE', name: 'Germany', dialCode: '+49', flag: flag('DE') },
  { code: 'GH', name: 'Ghana', dialCode: '+233', flag: flag('GH') },
  { code: 'GR', name: 'Greece', dialCode: '+30', flag: flag('GR') },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: flag('GT') },
  { code: 'GN', name: 'Guinea', dialCode: '+224', flag: flag('GN') },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flag: flag('GW') },
  { code: 'GY', name: 'Guyana', dialCode: '+592', flag: flag('GY') },
  { code: 'HT', name: 'Haiti', dialCode: '+509', flag: flag('HT') },
  { code: 'HN', name: 'Honduras', dialCode: '+504', flag: flag('HN') },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: flag('HK') },
  { code: 'HU', name: 'Hungary', dialCode: '+36', flag: flag('HU') },
  { code: 'IS', name: 'Iceland', dialCode: '+354', flag: flag('IS') },
  { code: 'IN', name: 'India', dialCode: '+91', flag: flag('IN') },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: flag('ID') },
  { code: 'IR', name: 'Iran', dialCode: '+98', flag: flag('IR') },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', flag: flag('IQ') },
  { code: 'IE', name: 'Ireland', dialCode: '+353', flag: flag('IE') },
  { code: 'IL', name: 'Israel', dialCode: '+972', flag: flag('IL') },
  { code: 'IT', name: 'Italy', dialCode: '+39', flag: flag('IT') },
  { code: 'JM', name: 'Jamaica', dialCode: '+1876', flag: flag('JM') },
  { code: 'JP', name: 'Japan', dialCode: '+81', flag: flag('JP') },
  { code: 'JO', name: 'Jordan', dialCode: '+962', flag: flag('JO') },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: flag('KZ') },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: flag('KE') },
  { code: 'KR', name: 'South Korea', dialCode: '+82', flag: flag('KR') },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', flag: flag('KW') },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', flag: flag('KG') },
  { code: 'LA', name: 'Laos', dialCode: '+856', flag: flag('LA') },
  { code: 'LV', name: 'Latvia', dialCode: '+371', flag: flag('LV') },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', flag: flag('LB') },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: flag('LS') },
  { code: 'LR', name: 'Liberia', dialCode: '+231', flag: flag('LR') },
  { code: 'LY', name: 'Libya', dialCode: '+218', flag: flag('LY') },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', flag: flag('LT') },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: flag('LU') },
  { code: 'MO', name: 'Macau', dialCode: '+853', flag: flag('MO') },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389', flag: flag('MK') },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: flag('MG') },
  { code: 'MW', name: 'Malawi', dialCode: '+265', flag: flag('MW') },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: flag('MY') },
  { code: 'MV', name: 'Maldives', dialCode: '+960', flag: flag('MV') },
  { code: 'ML', name: 'Mali', dialCode: '+223', flag: flag('ML') },
  { code: 'MT', name: 'Malta', dialCode: '+356', flag: flag('MT') },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', flag: flag('MR') },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', flag: flag('MU') },
  { code: 'MX', name: 'Mexico', dialCode: '+52', flag: flag('MX') },
  { code: 'MD', name: 'Moldova', dialCode: '+373', flag: flag('MD') },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', flag: flag('MN') },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', flag: flag('ME') },
  { code: 'MA', name: 'Morocco', dialCode: '+212', flag: flag('MA') },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: flag('MZ') },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: flag('MM') },
  { code: 'NA', name: 'Namibia', dialCode: '+264', flag: flag('NA') },
  { code: 'NP', name: 'Nepal', dialCode: '+977', flag: flag('NP') },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: flag('NL') },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: flag('NZ') },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: flag('NI') },
  { code: 'NE', name: 'Niger', dialCode: '+227', flag: flag('NE') },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: flag('NG') },
  { code: 'NO', name: 'Norway', dialCode: '+47', flag: flag('NO') },
  { code: 'OM', name: 'Oman', dialCode: '+968', flag: flag('OM') },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: flag('PK') },
  { code: 'PA', name: 'Panama', dialCode: '+507', flag: flag('PA') },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', flag: flag('PG') },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: flag('PY') },
  { code: 'PE', name: 'Peru', dialCode: '+51', flag: flag('PE') },
  { code: 'PH', name: 'Philippines', dialCode: '+63', flag: flag('PH') },
  { code: 'PL', name: 'Poland', dialCode: '+48', flag: flag('PL') },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: flag('PT') },
  { code: 'QA', name: 'Qatar', dialCode: '+974', flag: flag('QA') },
  { code: 'RO', name: 'Romania', dialCode: '+40', flag: flag('RO') },
  { code: 'RU', name: 'Russia', dialCode: '+7', flag: flag('RU') },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: flag('RW') },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: flag('SA') },
  { code: 'SN', name: 'Senegal', dialCode: '+221', flag: flag('SN') },
  { code: 'RS', name: 'Serbia', dialCode: '+381', flag: flag('RS') },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: flag('SC') },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: flag('SL') },
  { code: 'SG', name: 'Singapore', dialCode: '+65', flag: flag('SG') },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', flag: flag('SK') },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', flag: flag('SI') },
  { code: 'SO', name: 'Somalia', dialCode: '+252', flag: flag('SO') },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: flag('ZA') },
  { code: 'SS', name: 'South Sudan', dialCode: '+211', flag: flag('SS') },
  { code: 'ES', name: 'Spain', dialCode: '+34', flag: flag('ES') },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: flag('LK') },
  { code: 'SD', name: 'Sudan', dialCode: '+249', flag: flag('SD') },
  { code: 'SR', name: 'Suriname', dialCode: '+597', flag: flag('SR') },
  { code: 'SE', name: 'Sweden', dialCode: '+46', flag: flag('SE') },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: flag('CH') },
  { code: 'SY', name: 'Syria', dialCode: '+963', flag: flag('SY') },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', flag: flag('TW') },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', flag: flag('TJ') },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', flag: flag('TZ') },
  { code: 'TH', name: 'Thailand', dialCode: '+66', flag: flag('TH') },
  { code: 'TG', name: 'Togo', dialCode: '+228', flag: flag('TG') },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', flag: flag('TN') },
  { code: 'TR', name: 'Turkey', dialCode: '+90', flag: flag('TR') },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', flag: flag('TM') },
  { code: 'UG', name: 'Uganda', dialCode: '+256', flag: flag('UG') },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: flag('UA') },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: flag('AE') },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: flag('GB') },
  { code: 'US', name: 'United States', dialCode: '+1', flag: flag('US') },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: flag('UY') },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', flag: flag('UZ') },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: flag('VU') },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: flag('VE') },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: flag('VN') },
  { code: 'YE', name: 'Yemen', dialCode: '+967', flag: flag('YE') },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', flag: flag('ZM') },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: flag('ZW') },
]

/** Full ISO-3166 alpha-2 code → English name map, so every code resolves
 *  to a name even when it has no dial code entry above (territories,
 *  small states, etc.). Fallback only — COUNTRIES stays the source for
 *  dial codes and flags. */
const COUNTRY_NAMES: Record<string, string> = {
  AD: 'Andorra', AE: 'United Arab Emirates', AF: 'Afghanistan', AG: 'Antigua and Barbuda',
  AI: 'Anguilla', AL: 'Albania', AM: 'Armenia', AO: 'Angola', AQ: 'Antarctica',
  AR: 'Argentina', AS: 'American Samoa', AT: 'Austria', AU: 'Australia', AW: 'Aruba',
  AX: 'Åland Islands', AZ: 'Azerbaijan', BA: 'Bosnia and Herzegovina', BB: 'Barbados',
  BD: 'Bangladesh', BE: 'Belgium', BF: 'Burkina Faso', BG: 'Bulgaria', BH: 'Bahrain',
  BI: 'Burundi', BJ: 'Benin', BL: 'Saint Barthélemy', BM: 'Bermuda', BN: 'Brunei',
  BO: 'Bolivia', BQ: 'Bonaire, Sint Eustatius and Saba', BR: 'Brazil', BS: 'Bahamas',
  BT: 'Bhutan', BV: 'Bouvet Island', BW: 'Botswana', BY: 'Belarus', BZ: 'Belize',
  CA: 'Canada', CC: 'Cocos (Keeling) Islands', CD: 'DR Congo', CF: 'Central African Republic',
  CG: 'Republic of the Congo', CH: 'Switzerland', CI: "Côte d'Ivoire", CK: 'Cook Islands',
  CL: 'Chile', CM: 'Cameroon', CN: 'China', CO: 'Colombia', CR: 'Costa Rica',
  CU: 'Cuba', CV: 'Cape Verde', CW: 'Curaçao', CX: 'Christmas Island', CY: 'Cyprus',
  CZ: 'Czech Republic', DE: 'Germany', DJ: 'Djibouti', DK: 'Denmark', DM: 'Dominica',
  DO: 'Dominican Republic', DZ: 'Algeria', EC: 'Ecuador', EE: 'Estonia', EG: 'Egypt',
  EH: 'Western Sahara', ER: 'Eritrea', ES: 'Spain', ET: 'Ethiopia', FI: 'Finland',
  FJ: 'Fiji', FK: 'Falkland Islands', FM: 'Micronesia', FO: 'Faroe Islands', FR: 'France',
  GA: 'Gabon', GB: 'United Kingdom', GD: 'Grenada', GE: 'Georgia', GF: 'French Guiana',
  GG: 'Guernsey', GH: 'Ghana', GI: 'Gibraltar', GL: 'Greenland', GM: 'Gambia',
  GN: 'Guinea', GP: 'Guadeloupe', GQ: 'Equatorial Guinea', GR: 'Greece',
  GS: 'South Georgia and the South Sandwich Islands', GT: 'Guatemala', GU: 'Guam',
  GW: 'Guinea-Bissau', GY: 'Guyana', HK: 'Hong Kong', HM: 'Heard Island and McDonald Islands',
  HN: 'Honduras', HR: 'Croatia', HT: 'Haiti', HU: 'Hungary', ID: 'Indonesia',
  IE: 'Ireland', IL: 'Israel', IM: 'Isle of Man', IN: 'India', IO: 'British Indian Ocean Territory',
  IQ: 'Iraq', IR: 'Iran', IS: 'Iceland', IT: 'Italy', JE: 'Jersey', JM: 'Jamaica',
  JO: 'Jordan', JP: 'Japan', KE: 'Kenya', KG: 'Kyrgyzstan', KH: 'Cambodia',
  KI: 'Kiribati', KM: 'Comoros', KN: 'Saint Kitts and Nevis', KP: 'North Korea',
  KR: 'South Korea', KW: 'Kuwait', KY: 'Cayman Islands', KZ: 'Kazakhstan', LA: 'Laos',
  LB: 'Lebanon', LC: 'Saint Lucia', LI: 'Liechtenstein', LK: 'Sri Lanka', LR: 'Liberia',
  LS: 'Lesotho', LT: 'Lithuania', LU: 'Luxembourg', LV: 'Latvia', LY: 'Libya',
  MA: 'Morocco', MC: 'Monaco', MD: 'Moldova', ME: 'Montenegro', MF: 'Saint Martin',
  MG: 'Madagascar', MH: 'Marshall Islands', MK: 'North Macedonia', ML: 'Mali',
  MM: 'Myanmar', MN: 'Mongolia', MO: 'Macau', MP: 'Northern Mariana Islands',
  MQ: 'Martinique', MR: 'Mauritania', MS: 'Montserrat', MT: 'Malta', MU: 'Mauritius',
  MV: 'Maldives', MW: 'Malawi', MX: 'Mexico', MY: 'Malaysia', MZ: 'Mozambique',
  NA: 'Namibia', NC: 'New Caledonia', NE: 'Niger', NF: 'Norfolk Island', NG: 'Nigeria',
  NI: 'Nicaragua', NL: 'Netherlands', NO: 'Norway', NP: 'Nepal', NR: 'Nauru',
  NU: 'Niue', NZ: 'New Zealand', OM: 'Oman', PA: 'Panama', PE: 'Peru',
  PF: 'French Polynesia', PG: 'Papua New Guinea', PH: 'Philippines', PK: 'Pakistan',
  PL: 'Poland', PM: 'Saint Pierre and Miquelon', PN: 'Pitcairn', PR: 'Puerto Rico',
  PS: 'Palestine', PT: 'Portugal', PW: 'Palau', PY: 'Paraguay', QA: 'Qatar',
  RE: 'Réunion', RO: 'Romania', RS: 'Serbia', RU: 'Russia', RW: 'Rwanda',
  SA: 'Saudi Arabia', SB: 'Solomon Islands', SC: 'Seychelles', SD: 'Sudan',
  SE: 'Sweden', SG: 'Singapore', SH: 'Saint Helena', SI: 'Slovenia',
  SJ: 'Svalbard and Jan Mayen', SK: 'Slovakia', SL: 'Sierra Leone', SM: 'San Marino',
  SN: 'Senegal', SO: 'Somalia', SR: 'Suriname', SS: 'South Sudan', ST: 'São Tomé and Príncipe',
  SV: 'El Salvador', SX: 'Sint Maarten', SY: 'Syria', SZ: 'Eswatini',
  TC: 'Turks and Caicos Islands', TD: 'Chad', TF: 'French Southern Territories',
  TG: 'Togo', TH: 'Thailand', TJ: 'Tajikistan', TK: 'Tokelau', TL: 'Timor-Leste',
  TM: 'Turkmenistan', TN: 'Tunisia', TO: 'Tonga', TR: 'Turkey', TT: 'Trinidad and Tobago',
  TV: 'Tuvalu', TW: 'Taiwan', TZ: 'Tanzania', UA: 'Ukraine', UG: 'Uganda',
  UM: 'United States Minor Outlying Islands', US: 'United States', UY: 'Uruguay',
  UZ: 'Uzbekistan', VA: 'Vatican City', VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela', VG: 'British Virgin Islands', VI: 'U.S. Virgin Islands',
  VN: 'Vietnam', VU: 'Vanuatu', WF: 'Wallis and Futuna', WS: 'Samoa',
  YE: 'Yemen', YT: 'Mayotte', ZA: 'South Africa', ZM: 'Zambia', ZW: 'Zimbabwe',
}

export function getCountryByCode(code: string): CountryDialCode | undefined {
  return COUNTRIES.find((c) => c.code === code)
}

export function getCountryName(code: string): string {
  return getCountryByCode(code)?.name ?? COUNTRY_NAMES[code] ?? code
}

export function getDialCode(code: string): string {
  return getCountryByCode(code)?.dialCode ?? '+234'
}

/** Expected length of the national (subscriber) number, excluding dial code and trunk '0'. */
const PHONE_NUMBER_LENGTH: Record<string, [number, number]> = {
  AE: [9, 9],
  AU: [9, 10],
  BD: [10, 11],
  BR: [10, 11],
  CA: [10, 10],
  CI: [8, 10],
  CM: [9, 9],
  CN: [11, 11],
  DE: [10, 11],
  EG: [10, 10],
  ET: [9, 9],
  FR: [9, 9],
  GB: [10, 11],
  GH: [9, 10],
  ID: [10, 12],
  IN: [10, 10],
  JP: [10, 11],
  KE: [9, 10],
  KR: [10, 11],
  KW: [8, 8],
  MA: [9, 9],
  MX: [10, 11],
  MY: [9, 10],
  NG: [10, 11],
  NL: [9, 10],
  PH: [10, 10],
  PK: [10, 11],
  QA: [8, 8],
  RW: [9, 9],
  SA: [9, 10],
  SG: [8, 8],
  SN: [9, 9],
  TH: [9, 10],
  TR: [10, 11],
  TZ: [9, 10],
  UG: [9, 10],
  US: [10, 10],
  VN: [9, 11],
  ZA: [9, 10],
  ZM: [9, 9],
}

const DEFAULT_PHONE_NUMBER_LENGTH: [number, number] = [7, 15]

export function validatePhoneNumber(phone: string, countryCode: string): { valid: boolean; message?: string } {
  const digits = (phone ?? '').replace(/\D/g, '')
  if (!digits) {
    return { valid: false, message: 'Phone number is required' }
  }

  const dialDigits = (getDialCode(countryCode) ?? '').replace(/\D/g, '')
  const bare =
    digits.startsWith(dialDigits) && digits.length > dialDigits.length ? digits.slice(dialDigits.length) : digits

  const [min, max] = PHONE_NUMBER_LENGTH[countryCode] ?? DEFAULT_PHONE_NUMBER_LENGTH
  const valid = bare.length >= min && bare.length <= max
  if (valid) return { valid: true }

  const countryName = getCountryByCode(countryCode)?.name ?? 'this country'
  return {
    valid: false,
    message: min === max ? `${countryName} numbers are ${min} digits` : `${countryName} numbers are ${min}–${max} digits`,
  }
}
